{% set version = "1.4.5" %}

package:
  name: fastavro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fastavro/fastavro-{{ version }}.tar.gz
  sha256: fb5b4b46bd9f89be07921752bac952daa872a79f94fadf01f3679da906824424

build:
  number: 0
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - python
  host:
    - python
    - cython
    - pip
    - setuptools >=18.0
    - wheel
  run:
    - python
    - pytz

test:
  requires:
    - nose
    - flake8
    - pip
  imports:
    - fastavro
    - fastavro.io
  commands:
    - pip check

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  dev_url: https://github.com/fastavro/fastavro
  doc_url: https://fastavro.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - scottbelden
    - tebeka
