{% set name = "fastavro" %}
{% set version = "0.11.0" %}
{% set sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{name}}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt



requirements:
    build:
        - python
        - cython
        - setuptools
    run:
        - python

test:
    requires:
        - nose
        - flake8
    imports:
        - {{ name }}

about:
    home: https://github.com/tebeka/{{ name }}
    license: MIT
    summary: Fast read/write of AVRO files
    dev_url: https://github.com/tebeka/{{ name }}

extra:
    recipe-maintainers:
        - tebeka
