{% set name = "fastavro" %}
{% set version = "0.18.0" %}
{% set sha256 = "3c5091350df378b55d04d9a32c2114bb9000055408c3f3a2b62fa6c95a84b31e" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{name}}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
    build:
        - python
        - cython
        - setuptools
    run:
        - python

test:
    requires:
        - nose
        - flake8
    imports:
        - {{ name }}

about:
    home: https://github.com/tebeka/{{ name }}
    license: MIT
    summary: Fast read/write of AVRO files
    dev_url: https://github.com/tebeka/{{ name }}

extra:
    recipe-maintainers:
        - cpcloud
        - mariusvniekerk
        - scottbelden
        - tebeka
