{% set name = "fastavro" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 017df0b9ab88b7050aaeaa0f740bdcd44e423a613caeb5143ae643a99f10b017

build:
  number: 0
  skip: True  # [py<39]
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - numpy
    - cramjam
    - zstandard  #[not win]
    - lz4  # [not win]
    - pandas
  imports:
    - fastavro
    - fastavro.io
  commands:
    - pip check
    - fastavro --help

    {% set ignore_tests = "" %}
    # Missing dependency zlib_ng
    {% set ignore_tests = ignore_tests + " --ignore=tests/test_block_reader.py" %}

    # Cython specific issue: See details in https://github.com/fastavro/fastavro/issues/760#issuecomment-2909047759
    {% set ignore_tests = ignore_tests + " --deselect=tests/test_fastavro.py::test_regular_vs_ordered_dict_record_typeerror" %}

    - pytest -vv {{ ignore_tests }} tests

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  description: Fast Avro for Python
  dev_url: https://github.com/fastavro/fastavro
  doc_url: https://fastavro.readthedocs.io/

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - scottbelden
    - tebeka
