{% set name = "fastavro" %}
{% set version = "0.21.2" %}
{% set sha256 = "8cb16df617a3702c1be556eb3d2fdfa1654360f06b80696477715d95d7417da8" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    fn: {{name}}-{{ version }}.tar.gz
    url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - cython
        - setuptools
    run:
        - python

test:
    requires:
        - nose
        - flake8
    imports:
        - {{ name }}

about:
    home: https://github.com/fastavro/{{ name }}
    license: MIT
    summary: Fast read/write of AVRO files
    dev_url: https://github.com/fastavro/{{ name }}

extra:
    recipe-maintainers:
        - cpcloud
        - mariusvniekerk
        - scottbelden
        - tebeka
