{% set version = "0.22.3" %}

package:
  name: fastavro
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fastavro/fastavro-{{ version }}.tar.gz
  sha256: a862dcb93f81bd14d03b54506139f04066a96956d06c75c9fd46059443d44f31

build:
  number: 0
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python

test:
  requires:
    - nose
    - flake8
  imports:
    - fastavro

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  dev_url: https://github.com/fastavro/fastavro

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - scottbelden
    - tebeka
