{% set name = "fastavro" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 68f48aca2dd832c6cc0fb37a098d38e1c4f63fdcf236eea9aa7fa2fdcea62825

build:
  number: 0
  skip: true  # [py<39]
  script:
    - export FASTAVRO_USE_CYTHON=1  # [not win]
    - set FASTAVRO_USE_CYTHON=1  # [win]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - fastavro = fastavro.__main__:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - setuptools
    - wheel
  run:
    - python

{% set ignore_tests = "" %}
# Missing dependency zlib_ng
{% set ignore_tests = ignore_tests + " --ignore=tests/test_block_reader.py" %}
# Cython specific issue: See details in https://github.com/fastavro/fastavro/issues/760#issuecomment-2909047759
{% set ignore_tests = ignore_tests + " --deselect=tests/test_fastavro.py::test_regular_vs_ordered_dict_record_typeerror" %}

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - numpy
    - cramjam
    - zstandard  #[not win]
    - lz4  # [not win]
    - pandas
  imports:
    - fastavro
    - fastavro.__main__
    - fastavro._logical_writers_py
    - fastavro._read_common
    - fastavro._schema_common
    - fastavro._write_common
    - fastavro.const
    - fastavro.io.binary_decoder
    - fastavro.io.json_decoder
    - fastavro.io.json_encoder
    - fastavro.io.symbols
    - fastavro.read
    - fastavro.repository
    - fastavro.repository.base
    - fastavro.repository.flat_dict
    - fastavro.schema
    - fastavro.utils
    - fastavro.validation
    - fastavro.write
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - fastavro --help
    - pytest -vv {{ ignore_tests }} tests

about:
  home: https://github.com/fastavro/fastavro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast read/write of AVRO files
  description: Fast Avro for Python
  dev_url: https://github.com/fastavro/fastavro
  doc_url: https://fastavro.readthedocs.io/

extra:
  recipe-maintainers:
    - cpcloud
    - mariusvniekerk
    - scottbelden
    - tebeka