travis:
  secure:
    BINSTAR_TOKEN: ubB5XKTfe9OwYKu3twm4Y1NKj5vL8F2SFvB1xeCnQd+wp97JlsOOh1sDhHwqC6/NQKYfphcX66UwisRBt4zl+RYV63jWeS7mqHQAt1AAqKfWTlR+qlYFeyg60XcAwkBZUtAvjU7p1GfpB9Sw28NFc55IxPqXccuRqdvkO1oRvVIsCP5HcFN9MOMSnGUXMt5oAiaxRXtmxOO8t86zg++fwvZIPTOGB6HCbswTJ/aD7SJuqSJS512F0W0eGlmfpomtv3Igs3yClmwLj8ZCr/qs0msiwrXoqkU0kdd1sjM1+0CIG3ZurG9ERVm1o2nOfCMQkM7uCscE5cbWwSMX1R87h3Z6lUt9HRhe585Use86vdqrhbSej0AwjZn1RCxf7hMVmYwDXNWyNDTV/P1ccDC4vHfEwrPBf/P11dKZzeoq3ZjOasnKDf4Cg/eobkPJnd1WSrhlMUzpvJkQ/fDPD2v5WnECZrc4bchIPO/ptW/Pe2yrTvIFYJ/WquNDRVc6PcnVO4CZ2TuWXDjMIP/ii0OqUzlP53tFJEbQ4Xa/WyIP8ZalmbiT4AwDBmGNO87PQmz3TAPjOShQ/JKEnmlhwcn/F8EGdJQkq2wMNcRprdwXu43SUwRjnzrdxfJpOlaDjIscc8CYUGteKBtHGjOtk9mhPpKJ/EDTQ5y4DfmswFE2i+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
