travis:
  secure:
    BINSTAR_TOKEN: hkCKzNkyiiJ5+GocZwaAS00GWQHZcheBbp4iz8OpRgLfQlHmKIqIxlYbg4IK2czB20x1Q5jeOz0aJLIa6d4RR0XWqnD5+DbgQgGd2z6ZHmSAx+GJq4BAgiH2UHT5TbeSgIgry64/Ax/VA/I9yBA0WKnpJV+RSLZ4WvQ6p/KOCI+5vBzSrZZOZn39TuT3cU97IeoJHwTuniuXlgovppL+FlKZKgOEno43pgbw1SYPIsZ+4nNbZ2f0j4Dtxk9wYfVeHa2qKpJr8m617demTqZrru72jYxsRXlTF/JSyt7W0ly3yeRkxrOR+5K49836uUupas+TNImYGZU5iAoJBlPge1uj0oXnUyt8TbrIdyIh6RScGpnPF/uvHFkkRept+JQh38w+8e/YKkmHmMEyKSuVKl3XacOfbwZrloLnQS1V574wFi68kNrs1lLPhPlo2FLvW0Ih5G0Lu2+HE8rLPWdk8cY1DQLdH6WxBoKSRqVVFXSQgkA47rKA3c4MQNkFM0C3f0CmGoYJtbUZmE8OSKEte65/+6n6XI6rg9xK4B56blhmnBpvF1yY6uGLhb2mCbNx8hWOhKkUDop6UEcrUgv5eIdt0TbqvGHzPIXuUe7fW8qXYtdFF0M9K6ZTVLVriHfy1PA+egToc22JtBkBEDWn7J+L7/rLeJmCUE2lOXmpWJg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
